/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Components: typeof import('./../src/components/index.ts')['default']
    CPage: typeof import('./../src/components/CPage/index.vue')['default']
    CSearch: typeof import('./../src/components/CSearch/index.ts')['default']
    CTable: typeof import('./../src/components/CTable/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    'Index.d': typeof import('./../src/components/CPage/index.d.ts')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./../src/components/CSearch/src/index.tsx')['default']
    Type: typeof import('./../src/components/CSearch/type.ts')['default']
    UsePagination: typeof import('./../src/components/CTable/usePagination.ts')['default']
    UseSearch: typeof import('./../src/components/CSearch/useSearch.ts')['default']
    UseTable: typeof import('./../src/components/CTable/useTable.ts')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
